force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>TeamMember</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamMembers</relationshipLabel>
    <relationshipName>TeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamsAppController.cls
public with sharing class TeamsAppController {
	
	@AuraEnabled(Cacheable=true)
	public static List<Team__c> getListOfTeams() {
		return [
			SELECT Id, Name
			FROM Team__c
			ORDER BY Name
		];
	}

	@AuraEnabled(Cacheable=true)
	public static List<TeamMember__c> getTeamMembers(String team) {
		return [ 
			SELECT Id, Name, Team__r.Name, Skills__c 
			FROM TeamMember__c 
			WHERE Team__c =: team 
			ORDER BY Name 
			LIMIT 50 
		];
	}
}